version: '3'
services:
    jenkins:
        image: jenkins/jenkins:lts
        privileged: true
        user: jenkins
        restart: always
        ports:
          - 8083:8080
          - 50003:50000
        volumes:
        - C:\Users\dkaggs\Desktop\test:/var/jenkins_home
        - //var/run/docker.sock:/var/run/docker.sock
        - /usr/local/bin/docker:/usr/bin/docker