version: '3'
services:
    python:
        build: .
    jenkins:
        image: jenkins/jenkins:lts
        privileged: true
        user: root
        restart: always
        ports:
          - 8083:8080
          - 50003:50000
        volumes:
        - C:\Users\dkaggs\Desktop\ock:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock